var QuestionFormConstants = {
  UPDATE_QUESTION_FORM: "UPDATE_QUESTION_FORM",
  DELETE_QUESTION_FORM: "DELETE_QUESTION_FORM",
  CLEAR_QUESTION_FORM: "CLEAR_QUESTION_FORM",
  ADD_ANSWER_QUESTION_FORM: "ADD_ANSWER_QUESTION_FORM",
  DELETE_ANSWER_QUESTION_FORM: "DELETE_ANSWER_QUESTION_FORM"
};

module.exports = QuestionFormConstants;
