# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd6eae899794844f4e7505be5384401a33bd2face8f71eff22290d372a05b0c278456b794950af00b6ad2bc732048f828ed3b3ea77cc62769a8a3c65d8eef907

test:
  secret_key_base: 83329f3006173fb1c086e38bc8ca55bf819e497d9a34c7b78fc2a21e1738d39a16c6a809dad1c837d4c2ac0018b62f260c32ad06d3e7e04c7756ceebdda7bd14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
